### ISSUE TITLE
Consider changing the maven groupId

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-ee4j/metro-jax-ws#267]
This project still releases its Maven artifacts under the group id `com.sun.xml.ws`. Now that it is under the Eclipse umbrella, this does not seem to make much sense (to me, at least), and brings much confusion about which versions of the jaxb related artifacts are up to date. (See #41 and https://github.com/mojohaus/jaxws-maven-plugin/issues/86.)

Please consider changing the groupId to reflect the usual Eclipse conventions.

**Comment by lukasj** [comment]
Changing javax group ids to jakarta was a nightmare and caused a lot of issues already, therefore it is unlikely to happen; plug-in’s docs already mentions the history, see https://eclipse-ee4j.github.io/metro-jax-ws/jaxws-maven-plugin/

Note: I have never been involved in the MojoHouse hosted project; I got to current sources in 2011 and trying to keep this plugin up-to-date since then. Whatever has been done before, is completely out of my sight

**Comment by oliviercailloux** [comment]
> Changing javax group ids to jakarta was a nightmare and caused a lot of issues already, therefore it is unlikely to happen

Thanks for the reply. I believe there is a misunderstanding. This project did not change javax group ids to jakarta. It changed the package names. This is a nightmare indeed. My request is about changing the Maven groupId. A different thing.

**Comment by lukasj** [comment]
Before package names were changed, group/artifact ids were changed, ie javax.xml.ws:jaxws-api became jakarta.xml.ws:jakarta.xml.ws-api with unchanged package names. Problem with that approach today is that there exist two artifacts with same packages and that makes it non-trivial to allow existence/usage of both in one project

**Comment by oliviercailloux** [comment]
Oh, I see indeed [jakarta.xml.ws-api](https://search.maven.org/search?q=a:jakarta.xml.ws-api) on Maven Central. I suppose this is the move to jaxws-common that is referred to in the doc you linked to. 

This currently obscure group id is unfortunate, but at least things become clearer now in my mind. Thanks again for your answers.
